### PR TITLE
ENH Include summary in elemental area by default

### LINKED ISSUE #947: `getSummary()` does not function unless added from `provideBlockSchema()`
Summaries will only be included by graphql when the result of `getSummary()` is included from `provideBlockSchema()`. This doesn't seem to be documented. I'd suggest to include the summary in the block schema by default.

## Acceptance criteria
- [x] Strings returned from `getSummary()` appear as summary descriptions of blocks inside the `ElementalArea`
- [x] If nothing is returned, the default message displays
- [x] Documentation is updated appropriately

## PRs
- https://github.com/silverstripe/silverstripe-elemental/pull/948
- https://github.com/silverstripe/developer-docs/pull/93

### PR DESCRIPTION
**Pull request by micschk**
FIX #947

### CODE REVIEW

**Review by GuySartorelli — DISMISSED** [review]
Can you please also remove the implementation in `ElementContent`?
When the new `5` branch is created I'll target the PR there and merge it in for the next major. (It's possible this could cause summaries to appear in blocks where people don't want them if we change this behaviour for `4.x`)

**Comment by GuySartorelli** [comment]
I've retargetted this at the `5` branch. In addition to the change above please also rebase this PR against the `5` branch so CI runs correctly.

**Comment by GuySartorelli** [comment]
I've made the changes I requested above - someone else will need to review this now, though.

**Review by emteknetnz — APPROVED** [review]
Tested locally, works good

**Pull request merged**
