### PR TITLE
Reorder function

### PR DESCRIPTION
**Pull request by Jianbinzhu**
Updated reorder function to account for when there are duplicate Sort values of elements within an ElementalArea

### CODE REVIEW

**Comment by Jianbinzhu** [comment]
@ScopeyNZ I came across an issue where elements under the same ParentID have duplicate Sort value, and I can't seem to replicate that anymore. To fix existing records, I've created a sort all elements function. Please advise if there's a better way of doing this, thanks.

Screen Shot 2021-08-30 at 5 35 06 PM

**Comment by ScopeyNZ** [comment]
I don't really like the idea of a side effect of somebody reordering their elements is a long running "fix the whole thing", that also doesn't have any guarantee of respecting the order they chose.

If there's a bug in this code which will mess up the sort order then we should address that, but other than that, I'm thinking we shouldn't have the code be concerned with garbage data.

**Comment by brynwhyman** [comment]
This just came up in a different context, possibly a bit more information about the bug at play: https://github.com/silverstripe/silverstripe-elemental/issues/849#issuecomment-922536928

**Comment by chrispenny** [comment]
Just adding my $0.02.

As Bryn mentioned, I experienced this issue here https://github.com/silverstripe/silverstripe-elemental/issues/849#issuecomment-922536928 

I think we could avoid a lot of these instances simply by making sure that we don't set a `Sort` value on our blocks until they actually have a Parent.

**Comment by Jianbinzhu** [comment]
@brynwhyman  @chrispenny  Just found out that this solution is only partially working 😂 , it doesn't work when when have 2 elements with sort value of `1` and then trying to drag the second element to the top. `$elementToBeAfterID` on L72 will be 0 as the element to be after will be none. Which means that `$sortAfterPosition` will stay `0` and then we will be comparing `$sortAfterPosition 0` to `$currentPosition 1` and it won't hit that else condistion. I've created a task to fix the broken elements instead for now.

Another thing I found is that the duplicated sort value is caused by when an Elemental Block is archived and then restored

**Comment by chrispenny** [comment]
@Jianbinzhu good find with the archive restoration. Based on @ScopeyNZ's comment, this would be an area where we would want to fix the "restoration process" itself.

EG: Maybe we have it set the `Sort` to the max `Sort` value + 1 from that `Parent` (put it down the bottom) any time we bring an archived block back to life.

**Comment by ScopeyNZ** [comment]
In regards to the sort order on archive/publish. I think it would be fine to clear the sort order value when a block is archived. I'll raise an issue for sort being broken as elements are restored from the archive.

WRT this PR, I'm going to close it as I don't think it's the solution we're looking for. Thanks for the help getting to the bottom if this issue!

**Pull request closed without merging**
