### PR TITLE
BUGFIX: Ensure graphql3 compat in type name generation

### PR DESCRIPTION
**Pull request by unclecheese**
See https://github.com/silverstripe/silverstripe-elemental/pull/870#issuecomment-872611069

### CODE REVIEW

**Comment by tractorcow** [comment]
I have tested this and it works fine.

**Comment by kinglozzer** [comment]
Looks legit, should we target this at `4.6` instead of `4`? Looks like a candidate for a quick patch release

**Comment by unclecheese** [comment]
Yeah good point. 4.6.

**Comment by unclecheese** [comment]
Have rebased against 4.6. Will merge on green.

**Pull request merged**
