### PR TITLE
BUGFIX: Use new typeMapping graphql API

### PR DESCRIPTION
**Pull request by unclecheese**
Resolves https://github.com/silverstripe/silverstripe-elemental/issues/954

### CODE REVIEW

**Comment by unclecheese** [comment]
Merging ahead of green, because it is interdependent with this graphql fix: https://github.com/silverstripe/silverstripe-graphql/pull/431

**Comment by emteknetnz** [comment]
@unclecheese please don't self merge unapproved pull-requests on stable branches.  I'm less concerned about graphql4's `master` branch as it's non-stable, however elemental 4 is stable.  The build for this PR ended up [red](https://github.com/silverstripe/silverstripe-elemental/pull/955/checks) and probably would not have been merged in its current state

**Comment by emteknetnz** [comment]
I suppose its an unfortunate side-effect that the elemental 4 _graphql folder is effectively at non-stable level despite it being within stable branch

**Comment by unclecheese** [comment]
Well the folder itself is basically inert. It's explicitly including graphql 4.x-dev in the build matrix that makes this stable module dependent on an unstable module, and I think that's a fairly new thing. But interdependent PRs, infrequent as they may be, are just unavoidable in our setup as far as I can tell.

**Pull request merged**
