### PR TITLE
Free up the getDescription method to prevent it overriding db fields

### PR DESCRIPTION
**Pull request by michalkleiner**
The `getDescription` method is potentially overriding a Description db field on any extending class. 

The method was used only to get an addition to getTypeNice to display in the gridfield, possibly translated.

Let me know if this needs to be targetted at any other branch as it might be seen as a BC issue, should someone use this public, though otherwise quite narrow-focused, method somewhere else.

## Issue
- https://github.com/silverstripe/silverstripe-elemental/issues/1106

### CODE REVIEW

**Comment by ScopeyNZ** [comment]
Unfortunately we can't break SemVer justified by the likelihood of someone (not) using the API, as much as I wish that were true. This will have to be a change targeted at `master`. You're welcome to do a BC PR, that deprecates the method. You can leave in the changes made to `::getTypeNice` too.

**Comment by emteknetnz** [comment]
This pull request hasn't had any activity for a while. Are you going to be doing further work on it, or would you prefer to close it now?

**Comment by michalkleiner** [comment]
Yes @emteknetnz, just retargeted the PR.

**Comment by emteknetnz** [comment]
@michalkleiner are you still interested in this one?  I have no idea when the next major version of elemental will be released

**Comment by michalkleiner** [comment]
@emteknetnz can we merge as is since it now targets master? At least that won't get lost. I may then raise a separate PR deprecating the method.

**Comment by emteknetnz** [comment]
I'm OK with that, link through the deprecation PR and I'll merge this as is

**Comment by michalkleiner** [comment]
@emteknetnz — #953

**Comment by GuySartorelli** [comment]
@michalkleiner I've changed the base of this to the `6` branch - the commits will need to be reset ~but it might be worth waiting until https://github.com/silverstripe/silverstripe-elemental/pull/1196 has been merged first or you'll have to rebase again after to resolve conflicts.~

The CMS 5 PR has been merged and merged up now.

**Comment by GuySartorelli** [comment]
Replaced with https://github.com/silverstripe/silverstripe-elemental/pull/1203

**Pull request closed without merging**
